### ISSUE TITLE
Document all components with detailed specifications and usage guidelines, using the templates defined in our documentation.

### ISSUE THREAD

**Issue by Beelzebot777** [Beelzebot777/Pelusa-Docs-Public#3]
Components to document:
- [ ] Beelzebot777/Pelusa-FrontEnd-Strateger#30
- [ ] Beelzebot777/Pelusa-FrontEnd-Strateger#45
- [ ] Beelzebot777/Pelusa-FrontEnd-Strateger#33
- [ ] Beelzebot777/Pelusa-FrontEnd-Strateger#46
- [ ] Beelzebot777/Pelusa-FrontEnd-Strateger#31
- [ ] Beelzebot777/Pelusa-FrontEnd-Strateger#42
- [ ] Beelzebot777/Pelusa-FrontEnd-Strateger#44
- [ ] Beelzebot777/Pelusa-FrontEnd-Strateger#43
- [ ] Beelzebot777/Pelusa-FrontEnd-Strateger#40
- [ ] Beelzebot777/Pelusa-FrontEnd-Strateger#39
- [ ] Beelzebot777/Pelusa-FrontEnd-Strateger#36
- [ ] Beelzebot777/Pelusa-FrontEnd-Strateger#38
- [ ] Beelzebot777/Pelusa-FrontEnd-Strateger#35
- [ ] Beelzebot777/Pelusa-FrontEnd-Strateger#34
- [ ] Beelzebot777/Pelusa-FrontEnd-Strateger#32
- [ ] Beelzebot777/Pelusa-FrontEnd-Strateger#37
- [ ] Beelzebot777/Pelusa-FrontEnd-Strateger#41
